# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1orxtB0jStSYVU2mnKo0N4U_7KbTP18DN
"""

import gradio as gr
import requests

def predict_charges(age, bmi, children, sex_male, smoker_yes, region_northwest, region_southeast, region_southwest):
    input_data = {
        "age": age,
        "bmi": bmi,
        "children": children,
        "sex_male": sex_male,
        "smoker_yes": smoker_yes,
        "region_northwest": region_northwest,
        "region_southeast": region_southeast,
        "region_southwest": region_southwest
    }
    try:
        response = requests.post("https://27ac-35-201-169-180.ngrok-free.app/predict", json=input_data)
        response.raise_for_status()  # Raise an error for bad responses
        return response.json()['prediction']
    except requests.exceptions.RequestException as e:
        return f"Error: {e}"

iface = gr.Interface(fn=predict_charges,
                     inputs=["number", "number", "number", "number", "number", "number", "number", "number"],
                     outputs="number",
                     title="Medical Insurance Charges Prediction",
                     description="Enter the details to predict the insurance charges.")

iface.launch()