# -*- coding: utf-8 -*-
"""data_clean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sFe-Rlo8E5LlGAp-6pdW4-OcoRE_1gNc
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder, StandardScaler


data = pd.read_csv('medical_insurance.csv')


print("Missing values in each column:\n", data.isnull().sum())

plt.figure(figsize=(10, 6))
sns.boxplot(data['charges'])
plt.title('Box Plot of Charges')
plt.xlabel('Charges')
plt.show()

Q1 = data['charges'].quantile(0.25)
Q3 = data['charges'].quantile(0.75)
IQR = Q3 - Q1
data = data[(data['charges'] >= (Q1 - 1.5 * IQR)) & (data['charges'] <= (Q3 + 1.5 * IQR))]

data = pd.get_dummies(data, columns=['sex', 'smoker', 'region'], drop_first=True)

scaler = StandardScaler()
data[['age', 'bmi', 'children', 'charges']] = scaler.fit_transform(data[['age', 'bmi', 'children', 'charges']])

data.to_csv('cleaned_medical_insurance_New.csv', index=False)
print("Cleaned data saved to cleaned_medical_insurance.csv")

data.head(5)

