# -*- coding: utf-8 -*-
"""Model_Train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yr67H8uH8uxE0KCMlm-MWoRfqKPlRYG-
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score


data = pd.read_csv('/content/cleaned_medical_insurance_New.csv')


X = data.drop('charges', axis=1)
y = data['charges']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


model = RandomForestRegressor()


model.fit(X_train, y_train)

y_pred = model.predict(X_test)


mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Mean Squared Error: {mse}')
print(f'R^2 Score: {r2}')